In [91]:
import numpy as np
import pandas as pd

In [92]:
#APファイルの取り込み
df_ap = pd.read_csv('./wifidata/after/APlocations_group.csv')
group_number = df_ap.iloc[-1]['buildID']
print(group_number)
group_transition = np.zeros((group_number, group_number))
df_ap

49


AP  x_coordinate(m)  y_coordinate(m)  floor  buildID
0       Bldg1AP1          21534.0          32313.0    2.0        1
1       Bldg1AP2          21534.0          32313.0    2.0        1
2       Bldg1AP3          21534.0          32313.0    3.0        1
3       Bldg1AP4          21534.0          32313.0    3.0        1
4       Bldg1AP5          21534.0          32313.0    4.0        1
...          ...              ...              ...    ...      ...
1119  Bldg48AP69          14356.0          39196.0    NaN       48
1120  Bldg48AP70          14356.0          39196.0    NaN       48
1121  Bldg48AP71          14356.0          39196.0    NaN       48
1122  Bldg48AP72          14356.0          39196.0    NaN       48
1123         out              NaN              NaN    NaN       49

[1124 rows x 5 columns]

In [93]:
#transition_201XXX_kmeans_X.csvのAP->Groupへの変換
month = '201409'
for cluster in range(5):
    print('cluster = {0}'.format(cluster))
    df_transition = pd.read_csv('./wifidata/cluster/'+month+'/transition_'+month+'_kmeans_'+str(cluster)+'.csv',index_col=0)
    #グループに変換
    transition = df_transition.to_numpy()
    for i in range(len(transition)):
        print('i = {0}, from_group = {1}'.format(i, df_ap.iloc[i]['buildID']))
        for j in range(len(transition)):
            group_transition[df_ap.iloc[i]['buildID']-1][df_ap.iloc[j]['buildID']-1] += transition[i][j]

    pd.DataFrame(group_transition).to_csv('./wifidata/cluster/'+month+'/group_transition_'+month+'_kmeans_'+str(cluster)+'.csv')
    #行和で割る
    #group_transition_rate = group_transition
    #tsum = group_transition.sum(axis=1)
    #for c in group_transition.columns:
    #for c in range(len(group_transition)):
    #    group_transition_rate[c] = group_transition_rate[c]/tsum
        #group_transition_rate = group_transition_rate.fillna(0)
    #pd.DataFrame(group_transition_rate).to_csv('./wifidata/cluster/'+month+'/group_transition_rate_'+month+'_kmeans_'+str(cluster)+'.csv')

cluster = 0
i = 0, from_group = 1
i = 1, from_group = 1
i = 2, from_group = 1
i = 3, from_group = 1
i = 4, from_group = 1
i = 5, from_group = 1
i = 6, from_group = 1
i = 7, from_group = 1
i = 8, from_group = 1
i = 9, from_group = 1
i = 10, from_group = 1
i = 11, from_group = 1
i = 12, from_group = 1
i = 13, from_group = 1
i = 14, from_group = 1
i = 15, from_group = 1
i = 16, from_group = 1
i = 17, from_group = 1
i = 18, from_group = 1
i = 19, from_group = 1
i = 20, from_group = 1
i = 21, from_group = 1
i = 22, from_group = 1
i = 23, from_group = 1
i = 24, from_group = 1
i = 25, from_group = 1
i = 26, from_group = 1
i = 27, from_group = 1
i = 28, from_group = 1
i = 29, from_group = 1
i = 30, from_group = 2
i = 31, from_group = 2
i = 32, from_group = 2
i = 33, from_group = 2
i = 34, from_group = 2
i = 35, from_group = 2
i = 36, from_group = 2
i = 37, from_group = 2
i = 38, from_group = 2
i = 39, from_group = 2
i = 40, from_group = 2
i = 41, from_group = 2
i = 42, from_group = 2
i = 43, f

<ipython-input-93-75389c2555f1>:19: RuntimeWarning: invalid value encountered in true_divide
  group_transition_rate[c] = group_transition_rate[c]/tsum


cluster = 1
i = 0, from_group = 1
i = 1, from_group = 1
i = 2, from_group = 1
i = 3, from_group = 1
i = 4, from_group = 1
i = 5, from_group = 1
i = 6, from_group = 1
i = 7, from_group = 1
i = 8, from_group = 1
i = 9, from_group = 1
i = 10, from_group = 1
i = 11, from_group = 1
i = 12, from_group = 1
i = 13, from_group = 1
i = 14, from_group = 1
i = 15, from_group = 1
i = 16, from_group = 1
i = 17, from_group = 1
i = 18, from_group = 1
i = 19, from_group = 1
i = 20, from_group = 1
i = 21, from_group = 1
i = 22, from_group = 1
i = 23, from_group = 1
i = 24, from_group = 1
i = 25, from_group = 1
i = 26, from_group = 1
i = 27, from_group = 1
i = 28, from_group = 1
i = 29, from_group = 1
i = 30, from_group = 2
i = 31, from_group = 2
i = 32, from_group = 2
i = 33, from_group = 2
i = 34, from_group = 2
i = 35, from_group = 2
i = 36, from_group = 2
i = 37, from_group = 2
i = 38, from_group = 2
i = 39, from_group = 2
i = 40, from_group = 2
i = 41, from_group = 2
i = 42, from_group = 2
i = 43, f

KeyboardInterrupt: 

In [68]:
#duration_201XXX_kmeans_X.csvのAP->Groupへの変換
month = '201401'
for cluster in range(5):
    print('cluster = {0}'.format(cluster))
    df_duration = pd.read_csv('./wifidata/cluster/'+month+'/duration_'+month+'_kmeans_'+str(cluster)+'.csv',index_col=0)
    #グループに変換
    for i, row in enumerate(df_ap.itertuples()):
        df_duration.loc[df_duration['from'] == i, 'from'] = row.buildID
        df_duration.loc[df_duration['to'] == i, 'to'] = row.buildID
        #print(str(i+1)+'/'+str(len(df_ap)))
    df_duration.to_csv('./wifidata/cluster/'+month+'/group_duration_'+month+'_kmeans_'+str(cluster)+'.csv')

cluster = 0
cluster = 1
cluster = 2
cluster = 3
cluster = 4


In [69]:
#クラスタごとに平均系内人数を求める
def getGroupAggregation(group_duration, month, cluster):
    clients_list = []
    node_list = []
    duration_list = []
    duration_sum = 0
    node = 0
    for row in group_duration.itertuples():
        if pd.isnull(row[2]): #取り出した行がNULLの場合はcontinue
            continue
        elif int(row[2]) == 49:#外部から到着
            #print('outside')
            client = row[1] #client
            node = int(row[3]) #toを入れておく
            duration_sum = 0 #0に初期化
        elif int(row[3]) == node: #同じノードへの推移
            duration_sum += float(row[4])
        elif int(row[3]) != node: #他のノードへ移動
            duration_sum += float(row[4]) #たしてからリストに入れる
            clients_list.append(row[1])#リストへ登録
            node_list.append(node)
            duration_list.append(duration_sum)
            node = int(row[3]) #ノードの更新
            duration_sum = 0
         
    group_duration_aggregation = pd.DataFrame({'client': clients_list, 'node': node_list, 'duration': duration_list})
    group_duration_aggregation.to_csv('./wifidata/cluster/'+month+'/group_duration_aggregation_'+month+'_kmeans_'+str(cluster)+'.csv')
    
    #集約したデータフレームから拠点毎の平均滞在時間を算出
    #groupのIDは1~48,49は外部、0は使っていない
    node_number = 50
    limit = 3600 * 3 #(滞在時間は最大3時間とする)
    staytime = np.zeros(node_number)
    staycount = np.zeros(node_number)
    meanstay = np.zeros(node_number)
    for row in group_duration_aggregation.itertuples():
        if row.duration <= limit:
            staytime[int(row.node)] += float(row.duration)
            staycount[int(row.node)] += 1
    for i, val in enumerate(staycount):
        if val > 0:
            meanstay[i] = staytime[i] / val
    pd.DataFrame(meanstay).to_csv('./wifidata/cluster/'+month+'/group_mean_duration_'+month+'_kmeans_'+str(cluster)+'.csv')      

In [70]:
month = '201401'
for cluster in range(5):
    df_group_duration = pd.read_csv('./wifidata/cluster/'+month+'/group_duration_'+month+'_kmeans_'+str(cluster)+'.csv')
    getGroupAggregation(df_group_duration, month, cluster)

In [119]:
#推移確率 (対角要素を除いたものを作成)
month = '201409'
cluster = 4
transition = np.array(pd.read_csv('./wifidata/cluster/'+month+'/group_transition_'+month+'_kmeans_'+str(cluster)+'.csv',index_col=0))
#対角要素を0
for i in range(len(transition)):
    for j in range(len(transition)):
        if i == j:
            transition[i][j] = 0
#行和を計算
row_sum = transition.sum(axis=1)
list0 = [] #行和が0になるリスト
for i, val in enumerate(row_sum):
    if val == 0:
        list0.append(i)
transition = np.delete(transition, list0, 0) #行を削除
transition = np.delete(transition, list0, 1) #列を削除
print(transition)
row_sum = transition.sum(axis=1)#もう一度行和
print(row_sum)
for i in range(len(transition)):
    transition[i] = transition[i] / row_sum[i]
pd.DataFrame(transition).to_csv('./wifidata/cluster/'+month+'/group_transition_rate_'+month+'_kmeans_'+str(cluster)+'.csv')   

[[0.0000e+00 2.4410e+03 1.0590e+03 ... 2.9000e+01 5.3200e+02 4.0490e+03]
 [2.0020e+03 0.0000e+00 3.4283e+04 ... 5.3900e+02 1.5000e+02 1.3552e+04]
 [7.8200e+02 3.9136e+04 0.0000e+00 ... 1.4100e+02 4.2000e+01 4.0030e+03]
 ...
 [1.5000e+01 5.3900e+02 1.6700e+02 ... 0.0000e+00 6.0000e+00 1.2220e+03]
 [2.9700e+02 1.7000e+02 4.7000e+01 ... 6.0000e+00 0.0000e+00 6.5800e+02]
 [2.7680e+03 1.1572e+04 3.9890e+03 ... 1.2460e+03 8.6400e+02 0.0000e+00]]
[ 10550. 255703. 113269.   7438. 140220.   6781.  78865.  24585.   3112.
  43399.   1170.  28789.  63077.  65385.  11869.   7790.  25648.  66522.
  56949.  67623.   1017.  46227.  62763.  21169.  13059.  10630.  11561.
  15757.   7859.  16585.  18176.  47751.  11237.  65587.  27449.  20374.
  23883.    340.  15730.   2139.   5058.   2940.   3536.  57056.]
